Added preview for video element and minutes in video
polotno-project/polotno-studio pull request #37
Opened 2024-05-29 18:37 UTC by vlad-grigoryan

2024-06-04 02:05 UTC, lavrton requested changes

2024-06-04 02:05 UTC, lavrton commented on src/sections/videos-section.js
> +        }
This code is not "react-way". I think it that case, it is very possible to avoid touching DOM directly and instead control style, text content, etc video via usual component render.

2024-06-06 18:56 UTC, vlad-grigoryan commented on src/components/video-grid.js
> +                        ref={loadMoreRef}
The Intersection Observer API allows you to configure a callback that is called when a target element intersects the device’s viewport. In our case, loadMoreRef is the latest element of the array.

2024-06-06 18:58 UTC, vlad-grigoryan commented on src/sections/videos-section.js
> +  const handleSelectVideo = useCallback((video) => {
indeed, need also add memorization fo VideoGrid component, because in ever rerendering of  videoSection without handleSelectVideos usecallback it will rerender VideoGrid also , I will fix It .

2024-07-05 16:05 UTC, closed without merging